<?php

echo $this->form;

?>
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js" ></script>
<script type="text/javascript">
  $(document).ready(function() {
	$('input').blur(function() {

	  var label = $(this).parent().prev().find('label').attr('for');

	  var data = {};
	  var url = '/validate';

	  $('input').each(function() {
		data[$(this).attr('name')] = $(this).val();
	  });

	  $('.error-container').remove();

	  $.post(url, data, function(response) {

		console.log(data);

		for (var name in response) {
		  if (response.hasOwnProperty(name)) {

			var input = $('input[name="' + name + '"')[0];

			if (! input) {
			  return;
			}

			input = $(input);

			var container = $('<div class="error-container"></div>').insertAfter(input);

			for (var key in response[name]) {
				$('<span class="error">' + response[name][key] + '</span>').appendTo(container);
			}

		  }
		}

	  }, 'json');

	})

  });
</script>