<?php echo $this->doctype() ?>
<html>
<head>
  <meta charset="utf-8">
  <title>ZendSamples</title>

  <style>
    /*general style*/
    html, body { margin:0; padding:0;}
    header, hgroup, nav, section, article, aside, footer {display: block;}
    a {text-decoration:none; color:#000;}
    a:hover {text-decoration: underline;}
    hr {width: 380px}
    #wrapper {width: 600px; margin: 0 auto;}
    /*header area*/
    header {height: 100px; background: #00C;}
    hgroup h1 {color: #FFF; padding: 22px 0 0 20px;}
    /*nav area*/
    nav {width: 400px; height: 20px; background:#C66; margin-left: 200px;}
    nav ul {margin: 0 0 0 -10px;}
    nav li {float: left; list-style-type:none; padding: 0 10px;}
    /*section area*/
    section {width:400px; background: #CCC; margin-top: -20px;}
    hgroup h2 {color: #000; padding: 10px 0 0 10px;}
    article {width:400px; background: #CCC;}
    article p {padding: 10px;}
    /*aside area*/
    aside {width:200px; height: 605px; background: #666; float:right; margin-top: -1px;}
    hgroup h3 {color: #fff; padding: 10px 0 0 10px;}
    aside article {width:200px; background: #666; color:#FFF}
    /*footer area*/
    footer {height: 40px; background: #09F; margin-top: -16px;}
    footer p {padding: 10px 0 0 10px;}
  </style>

</head>

<body>
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>HTML5: Simple Website Layout Tutorial Using HTML 5</title>

  <style>
    /*general style*/
    html, body { margin:0; padding:0;}
    header, hgroup, nav, section, article, aside, footer {display: block;}
    a {text-decoration:none; color:#000;}
    a:hover {text-decoration: underline;}
    hr {width: 380px}
    #wrapper {width: 600px; margin: 0 auto;}
    /*header area*/
    header {height: 100px; background: #00C;}
    hgroup h1 {color: #FFF; padding: 22px 0 0 20px;}
    /*nav area*/
    nav {width: 400px; height: 20px; background:#C66; margin-left: 200px;}
    nav ul {margin: 0 0 0 -10px;}
    nav li {float: left; list-style-type:none; padding: 0 10px;}
    /*section area*/
    section {width:400px; background: #CCC; margin-top: -20px;}
    hgroup h2 {color: #000; padding: 10px 0 0 10px;}
    article {width:400px; background: #CCC;}
    article p {padding: 10px;}
    /*aside area*/
    aside {width:200px; height: 605px; background: #666; float:right; margin-top: -1px;}
    hgroup h3 {color: #fff; padding: 10px 0 0 10px;}
    aside article {width:200px; background: #666; color:#FFF}
    /*footer area*/
    footer {height: 40px; background: #09F; margin-top: -16px;}
    footer p {padding: 10px 0 0 10px;}
  </style>

</head>

<body>
<div id="wrapper">

  <?php echo $this->layout()->content; ?>


</div><!--End Wrapper-->

</body>
</html>

</body>
</html>